# templates/envoy-config.yaml
admin:
  access_log_path: /dev/null
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 5050 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: ingress_tcp
          cluster: {{ $podName }}-cluster

  clusters:
  - name: {{ $podName }}-cluster
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: {{ $podName }}-cluster
      endpoints:
      - lb_endpoints:
        {{- range $link := $topology.links }}
        {{- if eq $link.source $podName }}
        - endpoint:
            address:
              socket_address:
                address: {{ $link.target }}
                port_value: 5050
        {{- else if eq $link.target $podName }}
        - endpoint:
            address:
              socket_address:
                address: {{ $link.source }}
                port_value: 5050
        {{- end }}
        {{- end }}
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: {{ $podName }}
    filters:
    - name: envoy.filters.network.tcp_rate_limit
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_rate_limit.v3.TcpRateLimit
        stat_prefix: egress_tcp_rate_limit
        rate_limit_service:
          grpc_service:
            envoy_grpc:
              cluster_name: rate_limit_service
            timeout: 0.25s
        descriptors:
          {{- range $link := $topology.links }}
          {{- if eq $link.source $podName }}
          - key: remote_address
            value: {{ $link.target }}
          - key: bandwidth_limit
            value: {{ $link.bandwidth }}M
          {{- else if eq $link.target $podName }}
          - key: remote_address
            value: {{ $link.source }}
          - key: bandwidth_limit
            value: {{ $link.bandwidth }}M
          {{- end }}
          {{- end }}