apiVersion: apps/v1
kind: StatefulSet
{{- $topology := .Files.Get "nt_nodes10_p0.2_0b28e_1M.json" | fromJson }}

{{- range $node := $topology.nodes }}
{{- $podName := $node.id }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $podName }}
spec:
  serviceName: "bcgossip-svc"
  replicas: 1
  selector:
    matchLabels:
      app: {{ $podName }}
  template:
    metadata:
      labels:
        app: {{ $podName }}
    spec:
      containers:
        - name: gossip-node
          image: wwiras/gpbc10:v1
          ports:
            - containerPort: 5050
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
        - name: envoy-proxy
          image: envoyproxy/envoy:v1.73.7
          ports:
            - containerPort: 5050
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
      volumes:
        - name: envoy-config
          configMap:
            name: {{ $podName }}-envoy-config
{{- end }}