apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcgossip50nodes30mbps
spec:
  selector:
    matchLabels:
      run: bcgossip
  replicas: 50
  template:
    metadata:
      labels:
        run: bcgossip
      annotations:
        kubernetes.io/ingress-bandwidth: 30M    # Limit the inbound bandwidth of the pod.
        kubernetes.io/egress-bandwidth: 30M     # Limit the outbound bandwidth of the pod.
    spec:
      containers:
      - name: bcgossip-cont
        image: wwiras/bcgossip-grpc:v15  # Replace with your actual Docker image
        ports:
        - containerPort: 5050
