apiVersion: v1
kind: Service
metadata:
  name: bcgossip-svc
  labels:
    run: bcgossip
spec:
  clusterIP: None  # Headless Service
  ports:
  - port: 50051
    protocol: TCP
  selector:
    run: bcgossip
