version: '3.8'
services:
  node1:
    container_name: node1
    build: .
    environment:
      NODE_NAME: node1
      NEIGHBORS: node2,node3

  node2:
    container_name: node2
    build: .
    environment:
      NODE_NAME: node2
      NEIGHBORS: node1,node3

  node3:
    container_name: node3
    build: .
    environment:
      NODE_NAME: node3
      NEIGHBORS: node1,node2
