apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcgossip10nodes10Mbps
spec:
  selector:
    matchLabels:
      run: bcgossip
  replicas: 10
  template:
    metadata:
      labels:
        run: bcgossip
      annotations:
        kubernetes.io/ingress-bandwidth: 10M    # Limit the inbound bandwidth of the pod.
        kubernetes.io/egress-bandwidth: 10M     # Limit the outbound bandwidth of the pod.
    spec:
      containers:
      - name: bcgossip-cont
        image: wwiras/bcgossip-grpc:v15  # Replace with your actual Docker image
        ports:
        - containerPort: 5050
