# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gossip.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgossip.proto\x12\x06gossip\"F\n\rGossipMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"!\n\x0e\x41\x63knowledgment\x12\x0f\n\x07\x64\x65tails\x18\x01 \x01(\t\"\r\n\x0bPingRequest\"!\n\x0cPongResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\"(\n\x10\x42\x61ndwidthRequest\x12\x14\n\x0cpayload_size\x18\x01 \x01(\x05\"+\n\x11\x42\x61ndwidthResponse\x12\x16\n\x0e\x62\x61ndwidth_mbps\x18\x01 \x01(\x02\x32\xc9\x01\n\rGossipService\x12<\n\x0bSendMessage\x12\x15.gossip.GossipMessage\x1a\x16.gossip.Acknowledgment\x12\x31\n\x04Ping\x12\x13.gossip.PingRequest\x1a\x14.gossip.PongResponse\x12G\n\x10MeasureBandwidth\x12\x18.gossip.BandwidthRequest\x1a\x19.gossip.BandwidthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gossip_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GOSSIPMESSAGE']._serialized_start=24
  _globals['_GOSSIPMESSAGE']._serialized_end=94
  _globals['_ACKNOWLEDGMENT']._serialized_start=96
  _globals['_ACKNOWLEDGMENT']._serialized_end=129
  _globals['_PINGREQUEST']._serialized_start=131
  _globals['_PINGREQUEST']._serialized_end=144
  _globals['_PONGRESPONSE']._serialized_start=146
  _globals['_PONGRESPONSE']._serialized_end=179
  _globals['_BANDWIDTHREQUEST']._serialized_start=181
  _globals['_BANDWIDTHREQUEST']._serialized_end=221
  _globals['_BANDWIDTHRESPONSE']._serialized_start=223
  _globals['_BANDWIDTHRESPONSE']._serialized_end=266
  _globals['_GOSSIPSERVICE']._serialized_start=269
  _globals['_GOSSIPSERVICE']._serialized_end=470
# @@protoc_insertion_point(module_scope)
