apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gossip-statefulset
spec:
  serviceName: "bcgossip-svc"
  replicas: 6  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: bcgossip
  template:
    metadata:
      labels:
        app: bcgossip
    spec:
      containers:
        - name: gossip-node
          image: wwiras/gpbc:v1  # Replace with your Docker image name
          ports:
            - containerPort: 5050
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
            - name: secrets-volume
              mountPath: /app/secrets
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/secrets/key.json"
      volumes:
        - name: config-volume
          configMap:
            name: topology-config
        - name: secrets-volume
          secret:
            secretName: gossip-simulator-key