---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: statefulset-reader
  namespace: default  # Adjust if your StatefulSet is in a different namespace
rules:
- apiGroups: [""]
  resources: ["statefulsets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: statefulset-reader-binding
  namespace: default  # Adjust if necessary
subjects:
- kind: ServiceAccount
  name: default  # Or replace with the ServiceAccount your application uses
  namespace: default  # Adjust if necessary
roleRef:
  kind: Role
  name: statefulset-reader
  apiGroup: rbac.authorization.k8s.io