apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gossip-statefulset
spec:
  serviceName: "bcgossip-svc"
#  replicas: 10  # Start with 2 replicas for testing $(IMAGE_TAG)
  replicas: $(REPLICA_COUNT)
  selector:
    matchLabels:
      app: bcgossip
  template:
    metadata:
      labels:
        app: bcgossip
    spec:
      containers:
        - name: gossip-node
          image: wwiras/gpbc5:v1  # Replace with your Docker image name
          ports:
            - containerPort: 5050
          env:
            - name: BANDWIDTH_LIMIT
              value: $(SPEED)
            - name: NODES
              value: $(REPLICA_COUNT)



