# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bcgossip.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62\x63gossip.proto\x12\x08\x62\x63gossip\"F\n\rGossipMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"!\n\x0e\x41\x63knowledgment\x12\x0f\n\x07\x64\x65tails\x18\x01 \x01(\t2Q\n\rGossipService\x12@\n\x0bSendMessage\x12\x17.bcgossip.GossipMessage\x1a\x18.bcgossip.Acknowledgmentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bcgossip_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GOSSIPMESSAGE']._serialized_start=28
  _globals['_GOSSIPMESSAGE']._serialized_end=98
  _globals['_ACKNOWLEDGMENT']._serialized_start=100
  _globals['_ACKNOWLEDGMENT']._serialized_end=133
  _globals['_GOSSIPSERVICE']._serialized_start=135
  _globals['_GOSSIPSERVICE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
