# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bcgossip2.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62\x63gossip.proto\x12\x06gossip\"C\n\rGossipRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0f\n\x07payload\x18\x03 \x01(\t\"D\n\x0eGossipResponse\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0f\n\x07payload\x18\x03 \x01(\t2C\n\x06Gossip\x12\x39\n\x06Gossip\x12\x15.gossip.GossipRequest\x1a\x16.gossip.GossipResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bcgossip_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GOSSIPREQUEST']._serialized_start=26
  _globals['_GOSSIPREQUEST']._serialized_end=93
  _globals['_GOSSIPRESPONSE']._serialized_start=95
  _globals['_GOSSIPRESPONSE']._serialized_end=163
  _globals['_GOSSIP']._serialized_start=165
  _globals['_GOSSIP']._serialized_end=232
# @@protoc_insertion_point(module_scope)
