apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gossip-statefulset
spec:
  serviceName: "bcgossip-svc"
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: bcgossip
  template:
    metadata:
      labels:
        app: bcgossip
      annotations:
        kubernetes.io/ingress-bandwidth: {{ .Values.speed }}
        kubernetes.io/egress-bandwidth: {{ .Values.speed }}
    spec:
      containers:
        - name: gossip-node
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 5050
        - env:
            - name: BANDWIDTH
              value: "{{ .Values.speed }}"
            - name: NODES
              value: "{{ .Values.totalNodes }}"