
{{/* Include the python-role template */}}
{{- include "python-role.template" . | indent 0 }}

{{/* Include the bcgossip-svc template */}}
{{- include "bcgossip-svc.template" . | indent 0 }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-statefulset-{{ .Values.bandwidth }}
spec:
  serviceName: "bcgossip-svc"
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: bcgossip-1M
  template:
    metadata:
      labels:
        app: bcgossip-1M
        run: bcgossip
      annotations:
        kubernetes.io/egress-bandwidth: {{ .Values.bandwidth }}
    spec:
      containers:
        - name: gossip-node
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5050
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BANDWIDTH
              value: {{ .Values.bandwidth }}
            - name: NODES
              value: {{ .Values.totalNodes }}
          volumeMounts:
          - name: data
            mountPath: /data
      volumes:
      - name: data
        emptyDir: {}
  podManagementPolicy: Parallel
  {{- range $index, $node := until (.Values.replicas) }}
  - metadata:
      name: {{ $.Release.Name }}-{{ $index }}
  {{- end }}