apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gossip-statefulset
spec:
  serviceName: "bcgossip-svc"
  replicas: {{ .Values.totalNodes }}  # Start with 2 replicas for testing
  selector:
    matchLabels:
      app: bcgossip
  template:
    metadata:
      labels:
        app: bcgossip
#      annotations:
#        kubernetes.io/ingress-bandwidth: {{ .Values.bandwidth }}    # Limit the inbound bandwidth of the pod.
#        kubernetes.io/egress-bandwidth: {{ .Values.bandwidth }}
    spec:
      containers:
        - name: gossip-node
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 5050
          env:
            - name: NODES
              value: "{{ .Values.totalNodes }}"
            - name: LATENCY
              value: "{{ .Values.latency_ms }}"
            - name: CLUSTER
              value: "{{ .Values.cluster }}"
            - name: MODEL
              value: "{{ .Values.model }}"