
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcgossip50nodes120mi
spec:
  selector:
    matchLabels:
      run: bcgossip
  replicas: 50
  template:
    metadata:
      labels:
        run: bcgossip
    spec:
      containers:
      - name: bcgossip-cont
        image: wwiras/bcgossip-grpc:v15  # Replace with your actual Docker image
        ports:
        - containerPort: 5050
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "120Mi"
